export const JWT_SECRET = 'JWT_SECRET';
export const CLOUDINARY_CLOUD_NAME = 'CLOUDINARY_CLOUD_NAME';
export const CLOUDINARY_API_KEY = 'CLOUDINARY_API_KEY';
export const CLOUDINARY_API_SECRET = 'CLOUDINARY_API_SECRET';
export const STRIPE_SECRET_KEY = 'STRIPE_SECRET_KEY';
export const STRIPE_WEBHOOK_SECRET = 'STRIPE_WEBHOOK_SECRET';
export const MERCADOPAGO_ACCESS_TOKEN = 'MERCADOPAGO_ACCESS_TOKEN';
export const CLIENT_DOMAIN = 'CLIENT_DOMAIN';
